general:
  results_file: customnn.txt
model:
  name: Customized("custom_model_data", "static_nn_model", in_dim = 3, out_dim = 2)
  path: models/model_weights/SEA_0_1.pth
data:
  dataset: Customized("custom_model_data", "SEA_data")
  num_outputs: 2
  start: 5
  end: 6
specification:
  norm: .inf
  epsilon: 0.055
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
    lr_beta: 0.03
  mip:
    parallel_solvers: 8
    solver_threads: 4
    refine_neuron_time_percentage: 0.8
bab:
  branching:
    candidates: 5
    reduceop: max
  timeout: 600
