general:
  data_generator:
    SEA:
      noise: 0.0
      seed_1: 0
      seed_2: 1
      variant_1: 0
      variant_2: 1
      normalization: true
  dataset_name: SEA_0_1
  training:
    training_instances: 2000
    shuffle: false
    model: Net_3_2
    batch_size: 16
    epochs: 5
    optimizer: RMSprop
    learning_rate: 0.01
    visualize: true
