general:
  data_generator:
    HYP:
      n_features: 10
      n_drift_features: 2
      mag_change: 0.0001
      sigma: 0.0
      noise: 0.0
      seed_1: 109
      seed_2: 109
      normalization: false
  dataset_name: HYP_0001_5
  training:
    training_instances: 2000
    shuffle: false
    model: Net_10_2
    batch_size: 64
    epochs: 100
    optimizer: Adam
    learning_rate: 0.005
    visualize: true
