general:
  data_generator:
    SEA:
      noise: 0.0
      seed_1: 2
      seed_2: 3
      variant_1: 2
      variant_2: 3
      normalization: true
  dataset_name: SEA_2_3
  training:
    training_instances: 2000
    shuffle: false
    model: Net_3_2
    batch_size: 16
    epochs: 25
    optimizer: Adam
    learning_rate: 0.01
    visualize: true
