general:
  data_generator:
    SEA: #or HYP
      noise: 0.0
      seed_1: 2
      seed_2: 3
      variant_1: 2
      variant_2: 3
      normalization: True
  dataset_name: "SEA_2_3"
  training:
    training_instances: 2000
    shuffle: False
    model: "Net_3_2"
    batch_size: 32
    epochs: 25
    learning_rate: 0.005
    visualize: True